### ISSUE TITLE
Get rid of Ubuntu 18 base image

### ISSUE THREAD

**Issue by NiklasRosenstein** [kraken-build/kraken-base-image#36]
At Helsing, we soon won't need the Ubuntu 18 base image any longer. We should get rid of it at soon after a period of keeping it around just to be safe.

**Comment by cdbrkfxrpt** [comment]
we will also be dropping Python 3.6 at the same time

**Comment by j-baker** [comment]
Something that's worth noting here as well. We use these older images (afaik) so that when we produce binaries, they're compatible with a sufficiently old glibc version.

With cargo-zigbuild (which we use for maturin already), the zig linker tries hard to make you compatible with the glibc of your choosing. Essentially, my library built on head-of-develop Nix is compatible with Ubuntu 20.04 because Zig has made it so. You can even specify your required compatibility (e.g. compile for `aarch64-unknown-linux-gnu.2.17`).

This is all to say - if we switch the cargo dist task over to using the zig linker, we might well be able to drop 20.04, too.

**Comment by cdbrkfxrpt** [comment]
i don't think we can drop 20.04 anytime soon; the JetPack and BSPs we have running on Jetsons are based on it, and they were the blocker here. it's a bit of a slower moving world and not everything is already available for 22.04 yet.

**Comment by j-baker** [comment]
My understanding is that internally, the 18.04 kraken docker image has zero usage on services that are deployed on nVidia Jetsons, and the 20.04 image has no usage at all. Where the 18.04 is heavily used is on Rust services and clis which are then copied to Jetsons.

**Comment by NiklasRosenstein** [comment]
https://github.com/deadsnakes/issues/issues/251#issuecomment-1577489107

> ubuntu bionic 18.04 has just reached end-of-life and as such its packages will be deleted

Can't get Python installed installed via deadsnakes into the UBuntu 18.04 base image anymore, and we probably want to drop it by the mere fact that it reached EOL anyway.
